FROM ubuntu:latest

ARG DEBIAN_FRONTEND=noninteractive

RUN echo "==> Upgrading apk and installing system utilities ...." \
 && apt -y update \
 && apt-get install -y wget \
 && apt-get -y install sudo

RUN echo "==> Installing Python3 and pip ...." \  
 && apt-get install python3 -y \
 && apt install python3-pip -y

RUN echo "==> Install dos2unix..." \
  && sudo apt-get install dos2unix -y 

RUN echo "==> Install langchain requirements.." \
  && pip install --break-system-packages -U --quiet langchain_experimental langchain langchain-community langchain_google_genai \
  && pip install --break-system-packages chromadb \
  && pip install --break-system-packages tiktoken

RUN echo "==> Install jq.." \
  && pip install --break-system-packages jq

RUN echo "==> Install streamlit.." \
  && pip install --break-system-packages streamlit --upgrade

RUN echo "==> Adding dotenv ..." \
  && pip install --break-system-packages python-dotenv

RUN echo "==> Adding sentence transformers ..." \
  && pip install --break-system-packages sentence-transformers transformers

RUN echo "==> Adding dotenv ..." \
  && pip install --break-system-packages fastmcp

COPY /configuration_copilot /configuration_copilot/

RUN chmod +x /configuration_copilot/start.sh

CMD ["/configuration_copilot/start.sh"]

